apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: resume
spec:
  replicas: 1
  template:
    metadata:
      annotations:
        revision: "{{CF_REVISION}}"
      labels:
        app: resume
    spec:
      containers:
        - name: resume
          image: quay.io/dreamcodez/resume:{{CF_SHORT_REVISION}}
          ports:
            - containerPort: 33001
---
apiVersion: v1
kind: Service
metadata:
  name: resume
spec:
  selector:
    app: resume
  ports:
    - protocol: TCP
      port: 33001
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: resume
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: dreamcodez.cc
    http:
      paths:
      - backend:
          serviceName: resume
          servicePort: 33001
