service: example-site

frameworkVersion: "=1.26.1"

provider:
  name: aws
  runtime: nodejs8.10
  stage: prod
  region: us-east-1
  #profile: default

plugins:
  - serverless-finch

custom:
  client:
    distributionFolder: public
    bucketName: resume-public-345847e8-830a-40f2-86c7-4b6b351d463f
