service: example-site

frameworkVersion: "=1.26.1"

provider:
  name: aws
  runtime: nodejs8.10
  stage: prod
  region: us-east-1

plugins:
  - serverless-finch

custom:
  client:
    distributionFolder: public
    bucketName: dreamcodez.cc
