version: 0.2

#env:
#  variables:
#    PLACEHOLDER: foo
phases:
  install:
    commands:
      - . deploy/bin/init-deploy-env
      - env
  pre_build:
    commands:
      - /bin/bash deploy/bin/restore-container-build-cache
  build:
    commands:
      - /bin/bash deploy/bin/build-and-push-docker-image
  post_build:
    commands:
      - /bin/bash deploy/bin/save-container-build-cache
cache:
  paths:
    - container-build-cache.tar.gz
