version: 0.2

env:
  variables:
     KUBECONFIG: deploy/kubeconfig
phases:
  install:
    commands:
      - . deploy/bin/init-deploy-env
      - export BENCHMARK_START=$(now_millis)
      - /bin/bash deploy/bin/credstash-get-deploy-secrets
      - env
  pre_build:
    commands:
      - /bin/bash deploy/bin/start-docker-dind
      - sleep 2
      - /bin/bash deploy/bin/restore-container-build-cache
  build:
    commands:
      - /bin/bash deploy/bin/build-and-push-docker-image
      - /bin/bash deploy/bin/deploy-chart
      - export BENCHMARK_END=$(now_millis)
      - export BENCHMARK=$((BENCHMARK_END-BENCHMARK_START))
      - /bin/bash deploy/bin/notify-build-success
  post_build:
    commands:
      - /bin/bash deploy/bin/save-container-build-cache
cache:
  paths:
    - container-build-cache.tar.gz
