version: 0.2

phases:
  install:
    commands:
      - . deploy/bin/init-deploy-env
      - env
  pre_build:
    commands:
      - /bin/bash -xeu deploy/bin/start-docker-dind
      - /bin/bash -xu deploy/bin/restore-container-build-cache
      - aws s3 cp s3://deploy-1e16ccd6-002c-43ff-ab0c-455629a17d48/assets/fonts.tar.gz deploy/
  build:
    commands:
      - /bin/bash -xeu bin/build
      - yarn install
      - yarn serverless client deploy --no-confirm --no-delete-contents
      - /bin/bash -xeu deploy/bin/notify-build-success
  post_build:
    commands:
      - /bin/bash -xu deploy/bin/save-container-build-cache
cache:
  paths:
    - container-build-cache.tar.gz
