[build]
target = "index.html"
dist = "dist"

[watch]
watch = ["src", "index.html", "styles", "static"]

[serve]
address = "127.0.0.1"

# port will be provided by Playwright
[[hooks]]
stage = "pre_build"
command = "npm"
command_arguments = ["run", "build:css:prod"]
