name: Home Page (dreamcodez.cc)
on:
  push:
    branches:
      - main
jobs:
  build-and-push:
    permissions:
      contents: read
      id-token: write
    name: Build & Push Final Docker Image to GCR
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: "google-github-actions/auth@v2"
        with:
          workload_identity_provider: projects/1030275258687/locations/global/workloadIdentityPools/github-dreamcodez/providers/github
          service_account: github-docker-access@personal-sandbox-159823.iam.gserviceaccount.com
      - run: gcloud auth configure-docker us-west1-docker.pkg.dev --project=personal-sandbox-159823 --quiet
      - name: Build & Push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: us-west1-docker.pkg.dev/personal-sandbox-159823/dreamcodez-cc/web:${{ github.sha}}
      - uses: "google-github-actions/deploy-cloudrun@v2"
        with:
          project_id: personal-sandbox-159823
          region: us-west1
          service: dreamcodez-cc
          image: us-west1-docker.pkg.dev/personal-sandbox-159823/dreamcodez-cc/web:${{ github.sha}}
